### ISSUE TITLE
Support wifi direct?

### ISSUE THREAD

**Issue by loveSheet** [chainsx/lede-OrangePiZero-xr819#2]
I tried wpa_supplicant and wpa_cli to enable wifi direct but this not working.

**Comment by chainsx** [comment]
You should set your WIFI mode to Legacy first.

**Comment by chainsx** [comment]
You can edit `/etc/config/wirless` and delete the following lines:
```
option htmode 'HT20'
```

**Comment by loveSheet** [comment]
> /etc/config/wirless

I don't have that file.

So I tried to off HT function via wpa_supplicant.conf.

Here is my wpa_supplicant.conf for wifi direct function

`ctrl_interface=/var/run/wpa_supplicant

update_config=1
device_name=PRIYA-P2P
device_type=2-0050F204-1

network={
        disable_ht=1
}
`

But this didn't work like before.

And kworker hung task cause kerenl panic.

`INFO: task kworker/u:1:16 blocked for more than 120 seconds.
"echo 0 > /proc/sys/kernel/hung_task_timeout_secs" disables this message.
kworker/u:1     D c03938d4     0    16      2 0x00000000
Kernel panic - not syncing: hung_task: blocked tasks
Backtrace: =2-0050F204-1
[<c00129f8>] (dump_backtrace+0x0/0x104) from [<c038e910>] (dump_stack+0x18/0x1c)
 r7:c5ca1140 r6:000003f1 r5:c058b470 r4:c5ca1140
[<c038e8f8>] (dump_stack+0x0/0x1c) from [<c038eb04>] (panic+0x78/0x1b8)
[<c038ea8c>] (panic+0x0/0x1b8) from [<c0059490>] (watchdog+0x20c/0x244)
 r3:00000001 r2:c051a0a8 r1:00000007 r0:c049d1eb
 r7:c5ca1140_iface=1
[<c0059284>] (watchdog+0x0/0x244) from [<c004358c>] (kthread+0x8c/0x98)
[<c0043500>] (kthread+0x0/0x98) from [<c002fa44>] (do_exit+0x0/0x608)
 r6:c002fa44 r5:c0043500 r4:c5c27f34
Rebooting in 5 seconds..`

**Comment by chainsx** [comment]
That file will be generated by the system after the first boot.
